name: amplicon_benchmark
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pandas
  - biopython
  - snakemake-minimal
  - cutadapt
  - importlib_resources
  - tqdm
  - setuptools
